export enum OddsBlazeLeague {
    Bundesliga = "germany_bundesliga",
    CS2 = "cs2",
    EPL = "england_premier_league",
    LOL = "league_of_legends",
    MLB = "mlb",
    MLS = "united_states_major_league_soccer",
    NBA = "nba",
    NCAAF = "ncaaf",
    NFL = "nfl",
    NHL = "nhl",
    UFC = "ufc",
    Valorant = "valorant",
    WNBA = "wnba"
}

export enum OddsBlazeSGPSportsbooks {
    BALLY_BET = "bally_bet",
    BALLY_BET_COLORADO = "bally_bet_colorado",
    BETONLINE_PROP_BUILDER = "betonline_prop_builder",
    BETRIVERS = "betrivers",
    BETRIVERS_COLORADO = "betrivers_colorado",
    BETRIVERS_ONTARIO = "betrivers_ontario",
    BETSAFE_ONTARIO = "betsafe_ontario",
    BODOG = "bodog",
    BODOG_PROP_BUILDER = "bodog_prop_builder",
    BOVADA = "bovada",
    BOVADA_PROP_BUILDER = "bovada_prop_builder",
    CASUMO_ONTARIO = "casumo_ontario",
    DRAFTKINGS = "draftkings",
    DRAFTKINGS_ONTARIO = "draftkings_ontario",
    ESPN_BET = "espn_bet",
    FANDUEL = "fanduel",
    FANDUEL_ONTARIO = "fanduel_ontario",
    HARD_ROCK_BET = "hard_rock_bet",
    HARD_ROCK_BET_NEW_JERSEY = "hard_rock_bet_new_jersey",
    LADBROKES_AUSTRALIA = "ladbrokes_australia",
    NORTHSTAR_BETS_ONTARIO = "northstar_bets_ontario",
    PRIZEPICKS = "prizepicks",
    PRIZEPICKS_DEMONS = "prizepicks_demons",
    PRIZEPICKS_GOBLINS = "prizepicks_goblins",
    THESCORE_BET = "thescore_bet",
    THESCORE_BET_ONTARIO = "thescore_bet_ontario",
    UNIBET_UNITED_KINGDOM = "unibet_united_kingdom"
}

export enum OddsBlazeSportsbooks {
    BETFAIR_UNITED_KINGDOM = "betfair_united_kingdom",
    BETFRED_UNITED_KINGDOM = "betfred_united_kingdom",
    BETMGM = "betmgm",
    BETMGM_COLORADO = "betmgm_colorado",
    BETMGM_ONTARIO = "betmgm_ontario",
    BETONLINE = "betonline",
    BETPARX_NEW_JERSEY = "betparx_new_jersey",
    BOOMBET_AUSTRALIA = "boombet_australia",
    CAESARS_COLORADO = "caesars_colorado",
    CAESARS_ONTARIO = "caesars_ontario",
    CIRCA_SPORTS_NEVADA = "circa_sports_nevada",
    DRAFTKINGS_PICK6 = "draftkings_pick6",
    FANATICS = "fanatics",
    FLIFF = "fliff",
    HOTSTREAK = "hotstreak",
    LADBROKES_UNITED_KINGDOM = "ladbrokes_united_kingdom",
    PADDY_POWER_UNITED_KINGDOM = "paddy_power_united_kingdom",
    PARLAYPLAY = "parlayplay",
    PINNACLE = "pinnacle",
    POINTSBET = "pointsbet",
    POINTSBET_ONTARIO = "pointsbet_ontario",
    PRIME_SPORTS_NEW_JERSEY = "prime_sports_new_jersey",
    PROPHETX = "prophetx",
    PS3838 = "ps3838",
    SKY_BET_UNITED_KINGDOM = "sky_bet_united_kingdom",
    SLEEPER = "sleeper",
    SPORT_888_ONTARIO = "888sport_ontario",
    STAKE = "stake",
    TAB_AUSTRALIA = "tab_australia",
    UNDERDOG_FANTASY = "underdog_fantasy"
}